/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTasksIndexRouteImport } from './routes/admin/tasks.index'
import { Route as AdminTasksNewRouteImport } from './routes/admin/tasks.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTasksIndexRoute = AdminTasksIndexRouteImport.update({
  id: '/admin/tasks/',
  path: '/admin/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTasksNewRoute = AdminTasksNewRouteImport.update({
  id: '/admin/tasks/new',
  path: '/admin/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/users' | '/admin/tasks/new' | '/admin/tasks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/users' | '/admin/tasks/new' | '/admin/tasks'
  id: '__root__' | '/' | '/admin/users' | '/admin/tasks/new' | '/admin/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminTasksNewRoute: typeof AdminTasksNewRoute
  AdminTasksIndexRoute: typeof AdminTasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tasks/': {
      id: '/admin/tasks/'
      path: '/admin/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tasks/new': {
      id: '/admin/tasks/new'
      path: '/admin/tasks/new'
      fullPath: '/admin/tasks/new'
      preLoaderRoute: typeof AdminTasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminTasksNewRoute: AdminTasksNewRoute,
  AdminTasksIndexRoute: AdminTasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
