AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: UI

Parameters:
  StackName: # must be lower case
    Type: String
  DomainName:
    Type: String

Resources:
  SecurityHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub "${StackName}CustomSecurityHeadersPolicy"
        Comment: Security headers for CloudFront distribution
        #Enable if cors issues
        # CorsConfig:
        #   CorsBehavior:
        #     AccessControlAllowCredentials: true
        #     AccessControlAllowOrigins:
        #       Items:
        #         - "*"
        #     AccessControlAllowHeaders:
        #       Items:
        #         - "*"
        #     AccessControlAllowMethods:
        #         - GET
        #         - POST
        #         - OPTIONS
        #         - PUT
        #         - DELETE
        #         - PATCH
        #     AccessControlMaxAgeSec: 600
        #     OriginOverride: true
        SecurityHeadersConfig:
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 63072000
            IncludeSubdomains: true
            Override: true
            Preload: true
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: no-referrer
            Override: true
          XSSProtection:
            Protection: true
            ModeBlock: true
            Override: true

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${StackName}.${DomainName}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        Origins:
          - DomainName: !Sub "${StackName}.${DomainName}.s3-website-${AWS::Region}.amazonaws.com"
            Id: !Sub "${StackName}S3Origin"
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        DefaultCacheBehavior:
          TargetOriginId: !Sub "${StackName}S3Origin"
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy
        CacheBehaviors:
          - PathPattern: index.html
            TargetOriginId: !Sub "${StackName}S3Origin"
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - HEAD
              - GET
            CachedMethods:
              - HEAD
              - GET
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy #Comentar si la seguridad en index.html rompe
          - PathPattern: /static/js/*.js
            TargetOriginId: !Sub "${StackName}S3Origin"
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - HEAD
              - GET
            CachedMethods:
              - HEAD
              - GET
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy
        Enabled: true
        PriceClass: PriceClass_All

Outputs:
  CloudFrontDistributionId:
    Description: "CloudFront Distribution ID"
    Value: !Ref CloudFrontDistribution